<script>
  // Section 3, an instance on a set Ω of 4 points. Top: four σ-algebras drawn by
  // their blocks, from no information to complete information, with 2^N elements
  // for N blocks. Bottom: the 8 unions of blocks of the partition into 3 blocks.
  const DX = 34; // distance between two points
  const top = [
    { head: 'trivial', blocks: [[0, 3]], n: 2 },
    { head: 'generated by', it: 'A', blocks: [[0, 1], [2, 3]], n: 4 },
    { head: '3 blocks', blocks: [[0, 0], [1, 1], [2, 3]], n: 8 },
    { head: 'power set', blocks: [[0, 0], [1, 1], [2, 2], [3, 3]], n: 16 },
  ];
  const three = [[0, 0], [1, 1], [2, 3]];
  const unions = [[], [0], [1], [2], [0, 1], [0, 2], [1, 2], [0, 1, 2]];
  // Each name is a list of blocks (their indices) joined by ∪, or a plain symbol.
  const names = ['∅', [1], [2], [3], [1, 2], [1, 3], [2, 3], 'Ω'];
  const cap = ([a, b], x0, y, pad = 13) => ({ x: x0 + a * DX - pad, y: y - pad, w: (b - a) * DX + 2 * pad, h: 2 * pad });
</script>

<figure class="anim partitions">
  <svg viewBox="0 0 760 350" role="img" aria-label="Four sigma-algebras on four points drawn by their blocks, with 2, 4, 8 and 16 elements; below, the eight unions of blocks of a partition into three blocks">
    {#each top as t, k}
      {@const x0 = 45 + k * 185}
      <text class="head" x={x0 + 1.5 * DX} y="22">{t.head}{#if t.it}&nbsp;<tspan class="it">{t.it}</tspan>{/if}</text>
      {#each t.blocks as b}
        {@const r = cap(b, x0, 70)}
        <rect class="block" x={r.x} y={r.y} width={r.w} height={r.h} rx="13" />
      {/each}
      {#each [0, 1, 2, 3] as i}<circle class="pt" cx={x0 + i * DX} cy="70" r="5" />{/each}
      <text class="count" x={x0 + 1.5 * DX} y="118">{t.n} elements</text>
    {/each}
    <line class="rule" x1="30" y1="150" x2="730" y2="150" />
    <text class="head" x="380" y="176">the unions of the blocks B<tspan class="sub" dy="5">1</tspan><tspan dy="-5">,&nbsp;</tspan>B<tspan class="sub" dy="5">2</tspan><tspan dy="-5">,&nbsp;</tspan>B<tspan class="sub" dy="5">3</tspan></text>
    {#each unions as u, k}
      {@const x0 = 58 + (k % 4) * 185}
      {@const y = 214 + Math.floor(k / 4) * 74}
      {#each three as b, j}
        {@const r = cap(b, x0 + 10, y, 11)}
        <rect class="block small" class:on={u.includes(j)} x={r.x} y={r.y} width={r.w} height={r.h} rx="11" />
      {/each}
      {#each [0, 1, 2, 3] as i}<circle class="pt" cx={x0 + 10 + i * DX} cy={y} r="4" />{/each}
      <text class="name" x={x0 + 10 + 1.5 * DX} y={y + 28}>
        {#if typeof names[k] === 'string'}{names[k]}{:else}{#each names[k] as b, j}{#if j}<tspan dy="-5">&nbsp;∪&nbsp;</tspan>{/if}<tspan>B</tspan><tspan class="sub" dy="5">{b}</tspan>{/each}{/if}
      </text>
    {/each}
  </svg>
</figure>

<style>
  .partitions { margin: 1.5rem auto; max-width: 40rem; }
  svg { font-family: var(--anim-font); }
  .block { fill: none; stroke: var(--anim-ink); stroke-width: 1.3; }
  .block.small { stroke: var(--anim-muted); }
  .block.on { fill: var(--anim-accent); fill-opacity: 0.3; stroke: var(--anim-accent); }
  .pt { fill: var(--anim-ink); }
  .rule { stroke: var(--anim-rule); }
  text { fill: var(--anim-ink); font-size: 17px; text-anchor: middle; dominant-baseline: central; }
  .head { fill: var(--anim-muted); }
  .count { font-size: 16px; }
  .name { font-size: 16px; }
  .it { font-style: italic; }
  .sub { font-size: 12px; }
</style>
